name: Compilation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tensorrt8:
    name: 'NvidiaGpuTensorRT8'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/teddywesside1/foundationpose_base_dev:nvidia_gpu_tensorrt8_u2204
      options:
        --privileged
        --ipc host
        -v ${{ github.workspace }}:/workspace
        -w /workspace
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:
        cd /workspace && 
        mkdir build && cd build && 
        cmake .. && 
        make -j

  tensorrt10:
    name: 'NvidiaGpuTensorRT10'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/teddywesside1/foundationpose_base_dev:nvidia_gpu_tensorrt10_u2204
      options:
        --privileged
        --ipc host
        -v ${{ github.workspace }}:/workspace
        -w /workspace
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:
        cd /workspace && 
        mkdir build && cd build && 
        cmake .. && 
        make -j
